country_language_url.config:
  type: config_object
  label: 'Configuration of the module'
  mapping:
    country_language_manager:
      type: string
      label: 'Default country language manager plugin.'
